'''
Created on 10 Oct 2018

@author: esmipau
'''

import csv
import textwrap

def doStuff(inFile, outFile):
    sbDict = {}
    numSB = 0
    with open(outFile, 'w') as o:
        o.write('''# ASR Session description ini file 
# generated by parserASRDesc.py
# from %s 
#
# Not fit for human consumption

# The default section specifies the fields to be extracted from every processed event  
[DEFAULT]
keys=EVENT_PARAM_GLOBAL_CELL_ID EVENT_PARAM_ENBS1APID EVENT_PARAM_RAC_UE_REF 
        
''')
        with open(inFile,'r') as f:
            reader = csv.DictReader(f, delimiter=',', quotechar='"')
            for row in reader:
                ver = float(row['ASR-L version'])
                if ver > 1.0:
                    continue
                sbName = row['Field Name']
                if sbName in sbDict:
                    sbDict[sbName] = sbDict[sbName] + 1
                    sbName += '_%d'%(sbDict[sbName])
                else:
                    sbDict[sbName] = 1
                o.write('[%s]\n'%sbName)
                numSB += 1                    
                for val in row:
                    # clean up multiple spaces in the text
                    txt = ' '.join(row[val].split())
                    # clean up key field name
                    val = val.replace(' ','_')
                    val = val.replace('/','_')
                    val = val.replace('(','_')
                    val = val.replace(')','')
                    val = val.replace('#','num')

                    out = '%s = %s\n' % (val, txt)
                    txt = textwrap.wrap(out, width=78) 
                    o.write('%s\n'%('\n '.join(txt))) 
                o.write('\n')
    print('Wrote %d'%numSB)                
                
if __name__ == '__main__':
    inFile = '../schemaFiles/asr_pa9.csv'
    outFile = '../schemaFiles/asrSB.ini'
    doStuff(inFile, outFile)           